#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    vikram-wordpress-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^vikram-wordpress\.ddev\.site$`)
      
      service: "vikram-wordpress-web-80"
      tls: false
      # middlewares:
      #   - "vikram-wordpress-redirectHttps"
    vikram-wordpress-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^vikram-wordpress\.ddev\.site$`)
      
      service: "vikram-wordpress-web-8025"
      tls: false
      # middlewares:
      #   - "vikram-wordpress-redirectHttps"
    vikram-wordpress-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^vikram-wordpress\.ddev\.site$`)
      
      service: "vikram-wordpress-xhgui-80"
      tls: false
      # middlewares:
      #   - "vikram-wordpress-redirectHttps"
    
    
    
    vikram-wordpress-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^vikram-wordpress\.ddev\.site$`)
      
      service: "vikram-wordpress-web-80"
      
      tls: true
      
    vikram-wordpress-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^vikram-wordpress\.ddev\.site$`)
      
      service: "vikram-wordpress-web-8025"
      
      tls: true
      
    
    vikram-wordpress-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^vikram-wordpress\.ddev\.site$`)
      
      service: "vikram-wordpress-xhgui-80"
      
      tls: true
      
    

  middlewares:
    vikram-wordpress-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    vikram-wordpress-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-vikram-wordpress-web:80
        
    vikram-wordpress-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-vikram-wordpress-web:8025
        
    
    
    vikram-wordpress-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-vikram-wordpress-xhgui:80
        
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/vikram-wordpress.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/vikram-wordpress.key